- name: Install python
  apt:
    name: python3-pip
    update_cache: yes

- name: Install flask
  pip:
    name: flask

- name: Copy API
  copy:
    dest: /root/api.py
    content: |
      from flask import Flask, jsonify
      import random,time

      app = Flask(__name__)

      flag="FLAG0"
      t=0

      def getflag():
          global flag,t
          if time.time()-t>30:
              flag="FLAG_"+str(random.randint(1000,9999))
              t=time.time()
          return flag

      @app.route("/flag/user")
      def f():
          return jsonify({"flag":getflag()})

      if __name__=="__main__":
          app.run(host="0.0.0.0",port=8000)

- name: Run API
  shell: nohup python3 /root/api.py &
  async: 5
  poll: 0
